version: '3'
services:
  postgres-server:
    image: postgres
    #restart: always
    volumes:
      - data:/var/lib/postgresql/data
    
  api:
    build: .
    restart: always
    volumes:
      - .:/code
    env_file:
      - .env  

volumes:
  data: 